# environment.yml
name: edu-research
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.3
  - numpy>=1.21
  - scipy>=1.7
  - matplotlib>=3.5
  - seaborn>=0.11
  - jupyter
  - notebook
  - scikit-learn
  - statsmodels
  - pip
  - pip:
    - pingouin
    - researchpy
    - edu-analytics-tools
